services:
  production:
    build:
      context: .
      target: production-server
    ports:
      - "8009:80"
    volumes:
      - ./static:/usr/share/nginx/html/static
    profiles:
      - production

  development:
    build:
      context: .
      target: development-server
    ports:
      - "8009:3000"
    volumes:
      - ./static:/app/static
    profiles:
      - development
    restart: always
